language: node_js
node_js:
  - "4"
  - "6"
  - "node"
before_script: "npm install -g codeclimate-test-reporter"
after_script: "cat coverage/lcov.info | codeclimate"
addons:
  code_climate:
    repo_token: 5918a6fb9b25b4c60b68b6c25b3aa2ed99a1d754f22d502b35f0b22ec6768270
cache:
  yarn: true
  directories:
    - node_modules