language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
    - ~/.yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH=$HOME/.yarn/bin:$PATH
