language: node_js
node_js:
  - "4"
  - "6"
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/892f1bce89afd33af303